[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
evm_version = "paris"
[fuzz]
runs = 256

dotenv = ".env"

[rpc_endpoints]
sepolia = "${RPC_URL}"
